### ISSUE TITLE
No 'Access-Control-Allow-Origin' header present on error response

### ISSUE THREAD

**Issue by Chaphasilor** [WVV-Crowd-Sourced-Stock-Tracking/Backend#17]
**Describe the bug**
When submitting JSON data with incorrect keys, the server responds with a status of `400`, which is correct. It doesn't set the 'Access-Control-Allow-Origin' header though, causing JavaScript fetch requests to fail with a `CORS` error instead of returning the `400` code from the server. This makes it hard to debug.

**To Reproduce**

- Request Endpoint: for example ` /market/details `
- Request Method: ` POST `
- Request Headers:
```rest
Content-Type: application/json
```
- Request Body:
```json
{
  "mapsId": "ChIJD4Z5AOFzvUcRziQsyseWV0k"
}
```

**Expected behavior**
What should the endpoint return?
A `400` response with a 'Access-Control-Allow-Origin: *'-header.

**Actual behavior**
What _does_ the endpoint return?
A `400` response without the needed header

```
Unrecognized field "mapsId" (class webService.MarketDetailsRequest), not marked as ignorable (2 known properties: "maps_id", "market_id"])
 at [Source: org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream@469817d6; line: 2, column: 14] (through reference chain: webService.MarketDetailsRequest["mapsId"])
``` 

**Backend Version**
New or old?
New

**Comment by MartinLeiacker** [comment]
Will check the issue

**Comment by MartinLeiacker** [comment]
"Access-Control-Allow-Origin", "*" is now in a filter and will work also for error response.
Available by the next deployment

**Comment by dirkleiacker** [comment]
deployed
