### ISSUE TITLE
Läden zeigen in der Web-App immer geschlossen an

### ISSUE THREAD

**Issue by cube94** [WVV-Crowd-Sourced-Stock-Tracking/Backend#18]
**Describe the bug**
Im Front-End sind alle Läden geschlossen. Es gab schonmal ein ähnliches Ticket von Paul, aber scheint noch immer nicht zu funktionieren.

**Comment by van-den-Berg** [comment]
Kannst du uns bitte eine Beispielanfrage geben? Hast du schonmal die Frontend-Entwickler gefragt?
Danke :)

**Comment by Chaphasilor** [comment]
Das ist nicht mehr relevant, das neue Backend gibt uns die Öffnungszeiten zurück und wir zeigen somit den richtigen Status an :)
Funktioniert schon in unserem Test-Branch!

**Comment by Chaphasilor** [comment]
Das nächste Mal passt so ein Issue übrigens besser in's 'Web'-Repo 😉
