### ISSUE TITLE
Endpoint POST requests down

### ISSUE THREAD

**Issue by van-den-Berg** [WVV-Crowd-Sourced-Stock-Tracking/Backend#2]
23.08. ab 16:00  Waren die Endpoints für Post requests down. 
Mal in den Logs nachschauen was da los ist und möglicherweise Beheben.

Kurze Uptime von ca 2 Min um 16:38 rum.

**Comment by MartinLeiacker** [comment]
Wir gucken was da los ist. um 15:50 gab es ein Deploy mit einer neuen Funktion

**Comment by MartinLeiacker** [comment]
Wir haben das Problem lokalisiert. Es hat was mit den max. 500 Anfragen pro Tag an Google zu tun. Fabian ist da jetzt auch dran. Wir werden parallel weiter versuchen mehr Daten zu cachen.
