### ISSUE TITLE
Überreichen einer Liste an Produkten bei /market/transmit

### ISSUE THREAD

**Issue by van-den-Berg** [WVV-Crowd-Sourced-Stock-Tracking/Backend#4]
**Feature Implementierung:** 
Nicht nur das übermitteln eines einzelenen Produktes über /market/transmit, sondern das Übermitteln einer Liste an Produkten.

**Comment by MartinLeiacker** [comment]
Das haben wir gestern eingebaut. Siehe https://docs.google.com/document/d/1C6Kf6g5XpHomzMtpe7A9j9GRFllJ9KTcjBJALEP_1yQ/edit Übermitteln des Bestands in einem Supermarkt

JSON input Version 2 - deployed
{
    “bulk”: [{
               "market_id": 1,
              "product_id": 1,
               "quantity": 100
            }
        ]
      }
