### ISSUE TITLE
market/scrape Funktionalität für gefilterte Suche 

### ISSUE THREAD

**Issue by van-den-Berg** [WVV-Crowd-Sourced-Stock-Tracking/Backend#9]
Bei übergeben von ProductIDs erfolgt im Moment keine wirkliche Filterung der Läden nach Angebot vorgenommen, sondern nur die Produktliste gefiltert...

**Comment by van-den-Berg** [comment]
Bitte warten mit Implementierung bis Öffnungszeiten im Master sind.

**Comment by MartinLeiacker** [comment]
Ist im nächsten Deploy dabei. Es wird dann nach Anzahl verfügbarer Produkte, Distanz sortiert.
